backend:
  name: git-gateway
  branch: main  # The branch to update (match your repository's branch)
  commit_messages:
    create: "Create {{collection}} "{{slug}}""
    update: "Update {{collection}} "{{slug}}""
    delete: "Delete {{collection}} "{{slug}}""
    uploadMedia: "Upload "{{path}}""
    deleteMedia: "Delete "{{path}}""

# Media files will be stored in the repo under static/img/uploads
media_folder: "public/uploads"
public_folder: "/uploads"

# Collections define the structure for the different types of content
collections:
  # Blog posts collection
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"  # Path to the folder where the posts are stored
    create: true  # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Filename template
    editor:
      preview: false
    fields:  # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { 
          label: "Publish Date", 
          name: "date", 
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
          picker_utc: true
        }
      - { 
          label: "Author", 
          name: "author", 
          widget: "object",
          fields: [
            { label: "Name", name: "name", widget: "string" },
            { label: "Avatar", name: "avatar", widget: "image", required: false }
          ]
        }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          allow_add: true,
          required: false
        }
      - { 
          label: "Cover Image", 
          name: "cover", 
          widget: "image",
          required: false,
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - { 
          label: "Body", 
          name: "body", 
          widget: "markdown",
          buttons: ["bold", "italic", "link", "heading-two", "heading-three", "quote", "code", "bulleted-list", "numbered-list"],
          editor_components: ["image", "code-block"]
        }
      - { 
          label: "SEO", 
          name: "seo", 
          widget: "object",
          required: false,
          fields: [
            { label: "Meta Title", name: "title", widget: "string", required: false },
            { label: "Meta Description", name: "description", widget: "text", required: false },
            { label: "Social Image", name: "image", widget: "image", required: false }
          ]
        }
